/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Checkbox: typeof import('./src/components/Table/components/Checkbox/Checkbox.vue')['default']
    HeaderCell: typeof import('./src/components/Table/components/TableHeader/HeaderCell.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    PdfSignature: typeof import('./src/components/PdfSignature/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignatureDialog: typeof import('./src/components/PdfSignature/components/SignatureDialog.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
    TableBody: typeof import('./src/components/Table/components/TableBody/TableBody.vue')['default']
    TableCell: typeof import('./src/components/Table/components/TableBody/TableCell.vue')['default']
    TableHeader: typeof import('./src/components/Table/components/TableHeader/TableHeader.vue')['default']
    Tooltip: typeof import('./src/components/Table/components/Tooltip/Tooltip.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanButtonGroup: typeof import('vant/es')['ButtonGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanRate: typeof import('vant/es')['Rate']
    VanSlider: typeof import('vant/es')['Slider']
    VanStepper: typeof import('vant/es')['Stepper']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    VanUploader: typeof import('vant/es')['Uploader']
  }
}

// For TSX support
declare global {
  const Checkbox: typeof import('./src/components/Table/components/Checkbox/Checkbox.vue')['default']
  const HeaderCell: typeof import('./src/components/Table/components/TableHeader/HeaderCell.vue')['default']
  const IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
  const PdfSignature: typeof import('./src/components/PdfSignature/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SignatureDialog: typeof import('./src/components/PdfSignature/components/SignatureDialog.vue')['default']
  const Table: typeof import('./src/components/Table/index.vue')['default']
  const TableBody: typeof import('./src/components/Table/components/TableBody/TableBody.vue')['default']
  const TableCell: typeof import('./src/components/Table/components/TableBody/TableCell.vue')['default']
  const TableHeader: typeof import('./src/components/Table/components/TableHeader/TableHeader.vue')['default']
  const Tooltip: typeof import('./src/components/Table/components/Tooltip/Tooltip.vue')['default']
  const VanButton: typeof import('vant/es')['Button']
  const VanButtonGroup: typeof import('vant/es')['ButtonGroup']
  const VanConfigProvider: typeof import('vant/es')['ConfigProvider']
  const VanDialog: typeof import('vant/es')['Dialog']
  const VanEmpty: typeof import('vant/es')['Empty']
  const VanField: typeof import('vant/es')['Field']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanNavBar: typeof import('vant/es')['NavBar']
  const VanPopup: typeof import('vant/es')['Popup']
  const VanRadio: typeof import('vant/es')['Radio']
  const VanRadioGroup: typeof import('vant/es')['RadioGroup']
  const VanRate: typeof import('vant/es')['Rate']
  const VanSlider: typeof import('vant/es')['Slider']
  const VanStepper: typeof import('vant/es')['Stepper']
  const VanTabbar: typeof import('vant/es')['Tabbar']
  const VanTabbarItem: typeof import('vant/es')['TabbarItem']
  const VanTag: typeof import('vant/es')['Tag']
  const VanUploader: typeof import('vant/es')['Uploader']
}
